//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAD_BTNHOM.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Description { get; set; }
    }
}
